### ISSUE TITLE
Use posix-spawn to handle file upload operations?

### ISSUE THREAD

**Issue by replicat0r** [shrinerb/shrine#493] opened 2020-07-24 14:05 UTC
Thanks for the amazing plugin! It has been a pleasure integrating it into my app! 

RIght now my app is running on a pretty memory constraint system(2GB ram in total) with 2 spawned puma process, it usually takes about 1.4gb of memory. Now sometimes when users upload photos(photo have a limit of 5mb), I am running into 

`Cannot allocate memory - file`  in the promote job block. After doing some digging, it seems to that ruby has to copy the entirely of a parent process to fork something. The only fix for me is to restart the entire instance and restart the job. 

This gentlemen here with paperclip had the same issue

https://blog.sundaycoding.com/blog/2014/02/05/fighting-paperclip-errno-enomem-error/

Is it possible to use https://github.com/rtomayko/posix-spawn to spawn process for the promotejob attacher?

**Comment by jrochkind** [comment] 2020-07-24 14:54
I don't entirely understand the problem, but it should be possible for you to set up what you suggest. 

I would recommend looking into the backgrounding plugin. It basically gives you a hook to write whatever logic you want to be executed for promotion. The intended use is to use the backgrounding library of your choice to queue a job that will do the promotion. But it's completely agnostic as to what that is or how it will work. 

You would have to work out for yourself how to write it to use posix-spawn to do the promotion in a spawned process. But the backgrounding plugin docs will give you the arguments you need to communicate to the spawned process, and the logic the spawned process should execute with those arguments in order to execute promotion. 

HOWEVER, I wonder if you *really* want to be individually spawning processes for each promotion? I think this is probably not a great solution. If your goal is getting the promotion to happen in a separate process, I think I'd probably recommend using the background plugin with it's ordinary use case -- actually use a backgrounding library, such as sidekiq, to send promotion to there.  This is kind of what a backgrounding library is for, except instead of you manually spawning processes (possibly one for each promotion!), the backgrounding library is taking care of that plumbing for you, with a pool of persistent workers, and built-in patterns for handling failed jobs etc. The manual posix-spawn idea kind of sounds like reinventing a backgrounding library.

**Comment by aglushkov** [comment] 2020-07-24 15:00
@replicat0r 
You can configure mini-magick gem if you use it for processing https://github.com/minimagick/minimagick#errnoenomem

**Comment by janko** [comment] 2020-07-24 16:31
Both are @jrochkind and @aglushkov have good suggestions. If the memory load is coming from image processing, then tell MiniMagick to use posix-spawn, otherwise if you're using a process-based background job library (e.g. Resque), find a way to use posix-spawn there as well.

Since this is not a bug with Shrine, I will close this issue. In the future please post usage questions to the [Discourse channel](https://discourse.shrinerb.com/).

**Closed by janko** 2020-07-24 16:31 UTC
