### ISSUE TITLE
mime_type cannot open: No such file or directory

### ISSUE THREAD

**Issue by kashifnaseer** [shrinerb/shrine#303] opened 2018-10-23 17:08 UTC
I'm using **determine_mime_type** and it works fine most of time but some times, it gives **error mime_type cannot open No such file or directory** while same file can be uploaded after multiple tries.  any idea what is causing this ?

```json
{
  "id": "f972ca5ea746dfc641f390757a3acb7b",
  "storage": "cache",
  "metadata": {
    "filename": "Oman Integrated Residential Project.jpg",
    "size": 111662,
    "mime_type": "cannot open: No such file or directory",
    "cloudinary": {
      "public_id": "cache/c",
      "version": 1540305195,
      "signature": "c",
      "resource_type": "raw",
      "created_at": "2018-10-23T14:33:15Z",
      "tags": [],
      "bytes": 111662,
      "type": "upload",
      "etag": "c",
      "placeholder": false,
      "url": "http://res.cloudinary.com/ccc/raw/upload/v1540305195/cache/c",
      "secure_url": "https://res.cloudinary.com/ccc/raw/upload/v1540305195/cache/c",
      "original_filename": "file"
    }
  }
}
```

shrine Initializer code for determine_mime_type:

```rb
require "cloudinary"
require "shrine/storage/cloudinary"
require "shrine/storage/s3"

Shrine.storages = {
  cache: Shrine::Storage::Cloudinary.new(store_data: true, prefix: "cache", resource_type: :raw), 
  store: Shrine::Storage::Cloudinary.new(store_data: true),
  s3_cache: Shrine::Storage::S3.new(prefix: :cache, access_key_id: aws_settings['k'], region: 'eu-west-1', secret_access_key: aws_settings['k'], bucket: aws_settings['b']),
  s3: Shrine::Storage::S3.new(access_key_id: aws_settings['k'], region: 'eu-west-1', secret_access_key: aws_settings['k'], bucket: aws_settings['b'])
}

Shrine.plugin :activerecord
Shrine.plugin :cached_attachment_data
Shrine.plugin :determine_mime_type
```

**Comment by hmistry** [comment] 2018-10-23 18:20
I'm not sure. Could you provide a backtrace so I can see where the fail is occurring?

One thought I have is I know in S3 there can be some delay before a file is actually ready after it's uploaded to it so depending on your architecture and timing, you could be trying to download the file before it's available. I'm not sure if Cloudinary has a similar thing.

**Comment by janko-m** [comment] 2018-10-24 08:11
@hmistry It seems that no exception is actually being raised, and that the MIME type is silently stored as `cannot open: No such file or directory`, which is odd because we're raising an exception when an error happens in the `file` command.

**Comment by kashifnaseer** [comment] 2018-10-24 08:15
@janko-m any work around to fix this as our complete site is having issues due to it ?

**Comment by janko-m** [comment] 2018-10-24 08:29
It's interesting that when a `file` command is called with a path, and the path doesn't exist, the command will still return exit status `0`, as if everything was ok:

```
$ file foo
foo: cannot open `foo' (No such file or directory)
$ echo $?
0
```

However, I have no idea what could cause a `cannot open: No such file or directory` error when providing file content to the `file` command on *stdin*, as Shrine is doing. Currently Shrine is skipping calling the `file` command when the file is empty, and before it was calling it and `file` command would return `application/x-empty` MIME type, not an error.

@kashifnaseer Can you post here the output of `file --version` on the machine you're getting these errors from? Is there any way that you can reproduce this?

**Comment by janko-m** [comment] 2018-10-24 08:30
@kashifnaseer A workaround is switching to a different MIME type analyzer, for example:

```rb
# Gemfile
gem "mimemagic"
```
```rb
Shrine.plugin :determine_mime_type, analyzer: :mimemagic
```

**Comment by janko-m** [comment] 2018-10-24 08:37
@kashifnaseer Could you also include your Ruby and Shrine versions, as we requested in the issue template?

**Comment by kashifnaseer** [comment] 2018-10-24 08:45
@janko-m updated analyzer and it worked. Thanks :)

**Comment by janko-m** [comment] 2018-10-24 08:51
Once you switch to the new analyzer, you can fix the files that have an error with a code like this:

```rb
Record.find_each do |record|
  if record.attachment.mime_type == "cannot open: No such file or directory"
    attachment = record.attachment
    attachment.open do |io|
      attachment.data["mime_type"] = Shrine.determine_mime_type(io)
    end
    record.update(attachment_data: attachment.to_json)
    # or if `attachment_data` is an ActiveRecord JSON column:
    # record.update(attachment_data: attachment.data)
  end
end
```

Where you can replace `Record` with your model, and `attachment` with your attachment name.

**Comment by kashifnaseer** [comment] 2018-10-24 09:07
thanks @janko-m

**Comment by janko-m** [comment] 2018-10-24 11:00
@kashifnaseer Could you please give us the following information about the environment in which this error happened:

* Ruby version
* Shrine version
* `file --version`
* OS version (Linux distro and version)

We really want to get to the bottom of it, but it will be difficult if we don't have this information.

**Comment by kashifnaseer** [comment] 2018-10-24 11:03
@janko-m  sure- getting it

**Comment by janko-m** [comment] 2018-10-24 11:57
@kashifnaseer Thanks. Just to check, you are running your app on Mac OS in production?

**Comment by kashifnaseer** [comment] 2018-10-25 09:11
@janko-m no. its in development environment

**Comment by hmistry** [comment] 2018-10-25 15:11
@kashifnaseer That's great you can reproduce it in development. Could you provide us with a test script that reproduces the issue so we can investigate what's going on?

You can use one of the templates from here - https://github.com/shrinerb/shrine/blob/master/CONTRIBUTING.md

**Comment by janko-m** [comment] 2018-10-25 15:51
I tried reproducing the issue, but I get no errors:

```rb
require "shrine"
require "down"
require "concurrent"

Shrine.plugin :determine_mime_type

pool = Concurrent::FixedThreadPool.new(50)

image = Down.download("https://upload.wikimedia.org/wikipedia/commons/3/36/Hopetoun_falls.jpg")

10000.times do
  pool.post do
    File.open(image.path, "rb") do |file|
      raise if Shrine.determine_mime_type(file) != "image/jpeg"
    end
  end
end

pool.shutdown
pool.wait_for_termination
```

I'm running `file-5.35`, which is the newest version. So it's possible that between `file-5.25` (released 3 years ago) and `file-5.35` the bug was fixed.

We'll probably change the default MIME type analyzer to `mimemagic` or `marcel` in Shrine 3, as we cannot have Shrine behaviour change depending on the version of the `file` command is installed.

**Comment by hmistry** [comment] 2018-10-25 17:45
@janko-m I'd like to investigate it if @kashifnaseer can provide us a test script that reproduces it. It won't change our decision should we choose to replace the default analyzer. It'll help me gain a deeper understanding on files. 🙂

**Comment by janko-m** [comment] 2018-11-08 20:07
Closing due to lack of info that is necessary for us to determine the root cause. I've updated the `determine_mime_type` to raise a `Shrine::Error` in the case when `file` command exits successfully but returns an error on stdout, see https://github.com/shrinerb/shrine/pull/304.

If you're having troubles with this, here are some of the things you can try:

* update your `file` command package to the latest version.
* switch to a different MIME type analyzer (`mimemagic`, `marcel`, `filemagic`, `fastimage` etc)

Note that in Shrine 3 the default MIME type analyzer will probably be changed to `mimemagic` or `marcel`, which are pure ruby solutions. That way MIME type analysis will be the same regardless of the platform.

**Closed by janko-m** 2018-11-08 20:07 UTC
