### ISSUE TITLE
IO Error closed stream when uploading multiple images using cocoon gem

### ISSUE THREAD

**Issue by sree300994** [shrinerb/shrine#272] opened 2018-04-16 06:27 UTC
Ruby version:- 2.5.0
Rails Version:- 5.1.5
Im using cocoon gem and trying to upload multiple images with shrine, while creating i kept binding.pry and checked params of my controller at that it is showing like this

```
<ActionController::Parameters {"1523858951392"=><ActionController::Parameters {"image"=>#<ActionDispatch::Http::UploadedFile:0x007f6501475348 @tempfile=#<Tempfile:/tmp/RackMultipart20180416-5903-17lb4fb.jpg (closed)>, @original_filename="1 (1).jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"project[project_images_attributes][1523858951392][image]\"; filename=\"1 (1).jpg\"\r\nContent-Type: image/jpeg\r\n">, "_destroy"=>"false"} permitted: true>} permitted: true>
```

But in this i want image but it is showing some number like this in hash and it is dynamic for every creation and also image is closed for that i have written a custom method like this

```rb
def open_files
  params[:project][:project_images_attributes][:image].open if params[:project][:project_images_attributes][:image].present?
end
```
 please give me a solution about this problem

**Comment by janko-m** [comment] 2018-04-16 11:32
This looks like a duplicate of https://github.com/shrinerb/shrine/issues/107. See Ryan Bates' comment explaining the problem and the solution: https://github.com/shrinerb/shrine/issues/107#issuecomment-360879077

**Closed by janko-m** 2018-04-16 11:32 UTC
