### ISSUE TITLE
Derivatives are corrupted when submitting files without (or wrong) extensions

### ISSUE THREAD

**Issue by Roko131** [shrinerb/shrine#472] opened 2020-05-15 01:12 UTC
Nice job on the Gem, love the plugin system

### Brief Description
PNG images with no ext or wrong exts, like JPG instead of PNG 's derivatives are corrupted.

### Expected behavior
Derivatives should be created based on the actual uploaded file mime_type which is derived from the supported determine_mime_type plugin and be created correctly.

### Actual behavior
Uploaded file mime_type (png) was ignored, it was wrongly assumed to be JPG thus causing the  created derivative to be corrupted and unusable.

### Simplest self-contained example code to demonstrate issue
To use the example:

1. Change TEST_FOLDER_PATH
2. Use the image below (png), duplicate it 3 times, name each same as in code:
 - icon1_correct_png_ext.png
 - icon1_no_ext
 - icon1_with_wrong_jpg_ext.jpg
![icon1_correct_png_ext](https://user-images.githubusercontent.com/3532929/81999240-3267a680-965d-11ea-8a4e-1592a08c9371.png)
3. you can comment/uncomment the `testing` variable to test different files

When using the correct PNG extension the output derivative is good but when using a PNG image without extension. The output derivative is corrupted - why? it's not like the correct mime_type is unknown- Shouldn't it know to use the correct mime_type?

When assigning `testing` as `:png_image_without_ext` or `:png_image_with_jpg_ext` the output derivative has JPG extension and is corrupted:

corrupted file example - notice the jpg at the end which was added.
![corrupted_image_result](https://user-images.githubusercontent.com/3532929/81999400-9c804b80-965d-11ea-8af5-55fed46466a5.jpg)

```ruby
require "active_record"
require "shrine"
require "shrine/storage/file_system"
require 'image_processing'

TEST_FOLDER_PATH = '/path/to/folder/with/images'

Shrine.storages = {
  cache: Shrine::Storage::FileSystem.new(TEST_FOLDER_PATH, prefix: 'results/cache'), # temporary
  store: Shrine::Storage::FileSystem.new(TEST_FOLDER_PATH, prefix: 'results'),       # permanent
}

Shrine.plugin :activerecord
Shrine.plugin :derivatives # for different image sizes
Shrine.plugin :determine_mime_type
Shrine.plugin :validation_helpers


class MyUploader < Shrine
  # plugins and uploading logic
  Attacher.derivatives do |original|
    magick = ImageProcessing::MiniMagick.source(original)
    {
      thumbnail:  magick.resize_to_limit!(100, 100),
    }
  end

  Attacher.validate do
    puts "Mime Type for #{@file.metadata['filename']}: #{@file.mime_type}"
  end

end

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.connection.create_table(:posts) { |t| t.text :image_data }

class Post < ActiveRecord::Base
  include MyUploader::Attachment(:image)
end

# testing = :correct_png_ext
testing = :png_image_without_ext
# testing = :png_image_with_jpg_ext

case testing
when :correct_png_ext
  # when file has correct png extension the thumbnail derivative is ok
  post_with_correct_png_ext = Post.create(image: File.open("#{TEST_FOLDER_PATH}/icon1_correct_png_ext.png", 'rb'))
  post_with_correct_png_ext.image_derivatives!
when :png_image_without_ext
  # when file has no extension the thumbnail derivative is deformed, probably
  # because it is processed incorrectly as JPG, as you can see the jpg ext is being added
  post_without_ext = Post.create(image: File.open("#{TEST_FOLDER_PATH}/icon1_no_ext", 'rb'))
  post_without_ext.image_derivatives!
when :png_image_with_jpg_ext
  # same as no ext
  post_with_incorrect_ext = Post.create(image: File.open("#{TEST_FOLDER_PATH}/icon1_with_wrong_jpg_ext.jpg", 'rb'))
  post_with_incorrect_ext.image_derivatives!
end
```

### System configuration
Linux Ubuntu
**Ruby version**:
`ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]`
**Shrine version**:
`shrine (3.2.1)`

![ggg](https://user-images.githubusercontent.com/3532929/82000739-f4b94c80-9661-11ea-9cab-5eaffe822a9e.png)

**Comment by janko** [comment] 2020-05-15 07:35
Thank you for the detailed report! I was able to reproduce what you saw using the following script (I removed ActiveRecord, derivatives, validations etc as they weren't needed):

```rb
require "shrine"
require "down"
require "image_processing/mini_magick"

png_with_ext = Down.download("https://user-images.githubusercontent.com/3532929/81999240-3267a680-965d-11ea-8a4e-1592a08c9371.png")

# create files
png_without_ext   = Tempfile.new(["image"],         binmode: true)
png_with_jpeg_ext = Tempfile.new(["image", ".jpg"], binmode: true)

# copy content
File.write(png_without_ext.path,   File.binread(png_with_ext.path))
File.write(png_with_jpeg_ext.path, File.binread(png_with_ext.path))

# refresh file descriptors
png_without_ext.open
png_with_jpeg_ext.open

Shrine.plugin :determine_mime_type

puts Shrine.mime_type(png_with_ext)
puts Shrine.mime_type(png_without_ext)
puts Shrine.mime_type(png_with_jpeg_ext)

result1 = ImageProcessing::MiniMagick.source(png_with_ext).resize_to_limit!(100, 100)
result2 = ImageProcessing::MiniMagick.source(png_without_ext).resize_to_limit!(100, 100)
result3 = ImageProcessing::MiniMagick.source(png_with_jpeg_ext).resize_to_limit!(100, 100)

system "open #{result1.path}"
system "open #{result2.path}"
system "open #{result3.path}"

gets
```
```
image/png
image/png
image/png
```

<img height="400" alt="Screenshot 2020-05-15 at 09 34 00" src="https://user-images.githubusercontent.com/795488/82023883-3dd3c580-968f-11ea-8304-8a144607bc87.png">

It seems that in fact Shrine has correctly determined the MIME type, but ImageMagick apparently didn't handle the missing/incorrect extensions well (it has its own ways to determine the MIME type).

I would recommend using Shrine's `infer_extension` to set the correct extension on upload. You can use `:force` if you expect incorrect extensions. The following script demonstrates that with that the files get processed correctly:

```rb
require "shrine"
require "shrine/storage/memory"
require "down"
require "image_processing/mini_magick"

Shrine.storages[:memory] = Shrine::Storage::Memory.new

png_with_ext = Down.download("https://user-images.githubusercontent.com/3532929/81999240-3267a680-965d-11ea-8a4e-1592a08c9371.png")

# create files
png_without_ext   = Tempfile.new(["image"],         binmode: true)
png_with_jpeg_ext = Tempfile.new(["image", ".jpg"], binmode: true)

# copy content
File.write(png_without_ext.path,   File.binread(png_with_ext.path))
File.write(png_with_jpeg_ext.path, File.binread(png_with_ext.path))

# refresh file descriptors
png_without_ext.open
png_with_jpeg_ext.open

Shrine.plugin :determine_mime_type
Shrine.plugin :infer_extension, force: true

file1 = Shrine.upload(png_with_ext, :memory)
file2 = Shrine.upload(png_without_ext, :memory)
file3 = Shrine.upload(png_with_jpeg_ext, :memory)

result1 = file1.download { |f| ImageProcessing::MiniMagick.source(f).resize_to_limit!(100, 100) }
result2 = file2.download { |f| ImageProcessing::MiniMagick.source(f).resize_to_limit!(100, 100) }
result3 = file3.download { |f| ImageProcessing::MiniMagick.source(f).resize_to_limit!(100, 100) }

system "open #{result1.path}"
system "open #{result2.path}"
system "open #{result3.path}"

gets
```
<img height="400" alt="Screenshot 2020-05-15 at 09 32 48" src="https://user-images.githubusercontent.com/795488/82023770-0ebd5400-968f-11ea-927f-5f967771a2dd.png">

**Comment by Roko131** [comment] 2020-05-15 12:31
It works. Using `Shrine.plugin :infer_extension, force: true` indeed solves the problem.

Maybe worth adding the `force` option to the doc? It's undocumented:  https://shrinerb.com/docs/plugins/infer_extension

At first I used `Shrine.plugin :infer_extension`, without `force` and didn't understand why it failed the third test.
Thanks.

Also I'm trying to think if and where this case should be documented to prevent it from happening to others but can't really think of a good place, I guess in issues is sufficient enough.

**Comment by jrochkind** [comment] 2020-05-15 12:36
Good catch @Roko131, thanks!  I coincidentally noticed the docs didn't include this option a week ago, and already fixed it -- it just won't be live until the next shrine release (which is hopefully soon). 

(It's a lot of work to figure out what doc changes could be "backported" and released before the code release so we, similar to Rails, do not do it). 

Where is the main place for documentation of `ImageProcessing::MiniMagick`? I'd guess the `ImageMagick` gem?  I think it's worth pointing out in docs over there that MiniMagick (at least? maybe other processing plugins?) determines input media-type by file extension, so if it's wrong, it might not do what you want. It probably wouldn't be appropriate there to mention `infer_extension`, since ImageProcessing is not specific to shrine, but at least that would be a hint for someone to understand what's going on and then find infer_extension.  Maybe you want to submit a doc PR to ImageProcessing README?

**Comment by hmistry** [comment] 2020-05-23 19:34
Added documentation for the `force: true` option in the `infer_extension` plugin in commit 39f284d. Thanks for pointing it out @Roko131.

**Comment by jrochkind** [comment] 2020-05-24 01:02
@hmistry huh, I had done that 18 days ago here https://github.com/shrinerb/shrine/pull/465, I wonder what happened to the docs I spent time writing there, did they disappear somehow? 

Are you committing directly to master instead of making PRs, @hmistry?

**Comment by hmistry** [comment] 2020-05-24 01:34
@jrochkind I didn't see that because when I read the doc at shrinerb.com, it wasn't there due to being behind master. 
No worries, I'll revert my commit. Thanks for letting me know.

**Comment by janko** [comment] 2020-10-04 14:24
I'm closing this, as the main issue was that ImageMagick wasn't able to detect that an image is PNG without the `.png` extension, which is something that should be fixed in ImageMagick (and it seems it *was* fixed in recent versions). In comparison, libvips correctly detects PNG files without an extension.

**Closed by janko** 2020-10-04 14:24 UTC
