### ISSUE TITLE
Problem with creating GIF derivatives

### ISSUE THREAD

**Issue by dssjoblom** [shrinerb/shrine#530] opened 2021-03-31 07:47 UTC
### Brief Description

Creating GIF derivatives does not work as expected.

### Expected behavior

I'm expecting resized GIFs that work and look like the input image.

### Actual behavior

Two distinct problems:

1) Some derived GIFs render with artifacts. For example: https://media0.giphy.com/media/xT5LMAaXrdmXKAHAiI/source.gif. Uploading this file with Shrine and creating derivatives creates weird visual artifacts.

2) Sometimes the derivation fails. For example: https://privat.rejbrand.se/lorenz50.gif. Uploading this file does not work. The server hangs indefinitely in Imagemagick convert, which also consumes all CPU.

### Simplest self-contained example code to demonstrate issue

You can test the above GIFs with the following uploader:

```
require 'image_processing/mini_magick'

class BoardItemPicImageUploader < Shrine

  plugin :store_dimensions

  plugin :pretty_location

  plugin :url_options, store: {
           host: Rails.application.secrets.AWS_HOSTNAME
         }

  plugin :validation_helpers

  plugin :determine_mime_type, analyzer: :fastimage

  # Validate mime-type and size
  Attacher.validate do
    # Max 50MB
    validate_max_size 50*1024*1024

    validate_mime_type %w[image/jpeg image/jpg image/png image/gif]
  end

  plugin :default_url

  Attacher.default_url do |derivative: nil, **|
    "/image/#{derivative}/missing.png" if derivative
  end

  plugin :derivatives, create_on_promote: true

  Attacher.derivatives do |original|
    magick = ImageProcessing::MiniMagick.source(original)
    {
      medium:  magick.resize_to_fit!(650, nil),
      thumb: magick.resize_to_fit!(200, nil),
    }
  end
end
```

### System configuration
**Ruby version**: 2.7.2p137

**Shrine version**: 3.3.0

**Comment by janko** [comment] 2021-04-05 20:12
It's possible that default ImageMagick GIF processor doesn't handle GIFs well enough. You should probably report the issue there if you're able to reproduce it with an ImageMagick command.

Since this isn't an issue with Shrine, and it's unlikely to be an issue with ImageProcessing or MiniMagick gem, I'm closing this.

**Closed by janko** 2021-04-05 20:12 UTC

**Comment by dssjoblom** [comment] 2021-04-08 07:44
@janko I was able to get the first image to work by using the coalesce flag, based on https://github.com/minimagick/minimagick/issues/127 and https://askubuntu.com/questions/257831/how-can-i-resize-an-animated-gif-file-using-imagemagick

```
{
      medium:  magick.coalesce.resize_to_fit!(650, nil), # Add .coalesce
      thumb: magick.coalesce.resize_to_fit!(200, nil),
}
```

Maybe this could be added to the documentation, although it is more of an ImageMagick issue?

You are correct about the second image, it failed to convert even when running convert from the command line. It eventually ran out of memory:

```
convert-im6.q16: cache resources exhausted `lorenz50-out.gif' @ error/cache.c/OpenPixelCache/4083.
convert-im6.q16: memory allocation failed `lorenz50-out.gif' @ error/quantize.c/AssignImageColors/496.
```
