### ISSUE TITLE
How to use `generate_location` for a `presigned_endpoint`

### ISSUE THREAD

**Issue by abepetrillo** [shrinerb/shrine#485] opened 2020-06-17 16:20 UTC
I have posted a similar issue on discourse but I think this may actually be an issue with expected behavior

### Brief Description
I'm using the `presiogn_endpoint` plugin with an existing Uploader:

```
class AttachmentUploader < Shrine
  plugin :activerecord, callbacks: false
  plugin :presign_endpoint, {
    presign_options: -> (request) do
  	  filename     = request.params["filename"]
  	  extension    = File.extname(filename)
  	  content_type = Rack::Mime.mime_type(extension)

  	  {
  	    content_length_range: 0..(10*1024*1024),                     # limit filesize to 10MB
  	    content_disposition: "attachment; filename=\"#{filename}\"", # download with original  filename
  	    content_type:        content_type,                           # set correct content type
  	  }
    end,
    presign_location: -> (request) do
      ... ?
    end
end
}

def generate_location(io, context = {})
  "my/custom/folder/#{super}"
end

```

ActiveRecord class:
```
class Attachment < ActiveRecord::Base
  include AttachmentUploader::Attachment.new(:attachment)
...
```

Upon using this successfully, the AttachmentUploader class seems to completely ignore the `generate_location` method which _is_ used when doing direct uploads.

### Expected behavior
The presign endpoint should provide a key which defines the location based on the over-ridden `generate_location` instance method on the AttachmentUploader

### Actual behavior
The `generate_location` method is ignored and the file is uploaded to the root of the folder.

I did find the `presign_location` option, which may help me use this manually, but does this mean I have to create an Attachment record at this point? If an example can be provided here of how to simulate the direct upload location that would solve the issue I guess.

### System configuration
**Ruby version**:
2.4.9
**Shrine version**:
3.2.1

**Comment by BKSpurgeon** [comment] 2020-06-18 08:54
* Try: removing the presigned endpoint plugin and see if it saves the location you are after.
* When you mean you are "directly uploading" - are you uploading (i) directly to your app,  or (ii) directly to your bucket (and not to your app)?

**Comment by abepetrillo** [comment] 2020-06-18 13:33
How would you get the presigned endpoint if you remove the plugin? By "direct" I mean we avoid the browser hitting s3 and the app takes care of the file.

**Comment by abepetrillo** [comment] 2020-06-18 14:47
```
require "active_record"
require "shrine"
require "shrine/storage/memory"
require "shrine/storage/s3"
require "shrine/plugins/presign_endpoint"
require "down"
require 'pry'
require 'rest-client'
Pry.config.input = STDIN
Pry.config.output = STDOUT

Shrine.storages = {
  cache: Shrine::Storage::Memory.new
}

Shrine.storages[:store] = Shrine::Storage::S3.new(
  bucket:            ENV['S3_BUCKET_PRIVATE'],
  access_key_id:     ENV['S3_KEY_PRIVATE'],
  secret_access_key: ENV['S3_SECRET_PRIVATE'],
  region:            "us-east-1"
)

Shrine.plugin :activerecord


class MyUploader < Shrine
  # plugins and uploading logic

  def generate_location(io, context = {})
    "custom/location/#{super}"
  end

  plugin :presign_endpoint, {
    presign_options: -> (request) do
  	  filename     = request.params["filename"]
  	  extension    = File.extname(filename)
  	  content_type = Rack::Mime.mime_type(extension)

  	  {
  	    content_length_range: 0..(10*1024*1024),                     # limit filesize to 10MB
  	    content_disposition: "attachment; filename=\"#{filename}\"", # download with original filename
  	    content_type:        content_type,                           # set correct content type
  	  }
    end
  }
end

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.connection.create_table(:posts) { |t| t.text :image_data }

class Post < ActiveRecord::Base
  include MyUploader::Attachment(:image)
end

post = Post.create(image: Down.download("https://images.pexels.com/photos/2607443/pexels-photo-2607443.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260"))
puts "without s3 location:"
puts post.image_data
puts "with s3 location"
env = {
        "REQUEST_METHOD" => "GET",
        "SCRIPT_NAME"    => "",
        "PATH_INFO"      => "/s3/params",
        "QUERY_STRING"   => "filename=foo.txt",
        "rack.input"     => StringIO.new,
      }
status, content, presigned_endpoint = MyUploader.presign_response(:store, env)
endpoint = JSON.parse(presigned_endpoint.first)
fields = endpoint["fields"]
url = endpoint["url"]
puts "url: #{url}"
RestClient.post(url, fields.merge("file" => Down.download("https://images.pexels.com/photos/2607443/pexels-photo-2607443.jpeg?auto=compress&cs=tinysrgb&h=750&w=1260")))
# This is where I am stuck? Where is the post related to this file? What is the developer expected to do to generate a post?
# Also observe that the file is in the bucket, but not in "/custom/location"
```

**Comment by abepetrillo** [comment] 2020-06-18 15:05
The only thing that comes to mind is that I should put this in the cache, save a record in the database with a reference to the cache, then "promote" the file in an activerecord callback maybe?

**Comment by jrochkind** [comment] 2020-06-18 15:08
>  I should put this in the cache, save a record in the database with a reference to the cache, then "promote" the file in an activerecord callback maybe?

Hm, that is normal flow for shrine, and the file will normally be promoted in an activerecord callback by the shrine activerecord plugin for you, you don't need to set it up yourself.

**Comment by abepetrillo** [comment] 2020-06-18 15:11
It only relates in that I'm hoping by "promoting" the file, the file would be moved to it's proper location, and the validations would be run that are defined in the `validation_helpers` plugin

**Comment by abepetrillo** [comment] 2020-06-18 19:40
Should I log a separate issue about presign_endpoint ignoring the `validation_helpers` plugin?

**Comment by janko** [comment] 2020-06-18 22:11
The presign_endpoint plugin doesn't use `Shrine#generate_location`, because that method was designed to take a file as an argument, and the presign_endpoint doesn't have access to the file (since the file will be uploaded directly to the storage service). If you really want to share locations, you can extract the location generation logic into a class/constant and reuse it in `#generate_location` and `:presign_location`.

> I did find the presign_location option, which may help me use this manually, but does this mean I have to create an Attachment record at this point? If an example can be provided here of how to simulate the direct upload location that would solve the issue I guess.

You don't need to create a database record to generate a cached location for the file. Generally this is not possible in scenarios where you're directly uploading a file for a record that hasn't been created yet.

> It only relates in that I'm hoping by "promoting" the file, the file would be moved to it's proper location, and the validations would be run that are defined in the validation_helpers plugin.

Yes, that's what will happen. Have you not verified this already by saving the record after direct upload?

> Should I log a separate issue about presign_endpoint ignoring the validation_helpers plugin?I 

This is expected, the presign_endpoint doesn't have access to the file, and thus cannot validate its metadata. Direct uploads rely on client-side validations, which JS libraries like Uppy provide. The Shrine validations are run once the directly uploaded file is submitted and assigned to the model. 

Since both of the behaviours you mentioned are intended and have design reasoning behind them, I will close this issue.

**Comment by abepetrillo** [comment] 2020-06-19 12:06
This seems to be avoiding the confusion around how this should all integrate.

 > The presign_endpoint plugin doesn't use Shrine#generate_location, because that method was designed to take a file as an argument, and the presign_endpoint doesn't have access to the file (since the file will be uploaded directly to the storage service)

The only thing I would need in my given situation is not the file, but the `context`. Is there a predetermined way to do this?

> You don't need to create a database record to generate a cached location
That's not what I'm suggesting. I'm trying to figure out how you would expect this flow to work with the `activerecord` plugin. Right now you upload the file, then create a record via another endpoint with all the details (including the s3 key). W are basically trusting the client to give us the correct information as it stands. To put this another way, when do you expect the `Attacher.validate` block to be called? I ask because this is not called on `record.create`.

> This is expected, the presign_endpoint doesn't have access to the file, and thus cannot validate its metadata.
No but there is the option of passing the metadata up to the server. Which is what we have to do anyway. If not, at one point does the ruby application gain access to the file to decide things like generate_location. I'm not sure by your explanation above if you agree that the `promote` method is the correct way to go?

**Comment by janko** [comment] 2020-06-19 12:52
> The only thing I would need in my given situation is not the file, but the context. Is there a predetermined way to do this?

The `context` hash contains various available information at various stages of upload. Some information like the record or attachment name are not available during direct upload, and for presign_endpoint the uploader isn't even called, only the storage directly. What specific information do you expect to during presigning which isn't there?

> Right now you upload the file, then create a record via another endpoint with all the details (including the s3 key). 

The direct upload doesn't create any _records_, it's just uploading the file to the storage.

> We are basically trusting the client to give us the correct information as it stands. To put this another way, when do you expect the Attacher.validate block to be called? I ask because this is not called on record.create.

Shrine validations are run when you assign a file to a record, be it raw file that needs to be uploaded, or an already uploaded file in form of JSON or Hash data:

```rb
require "active_record"
require "shrine"
require "shrine/storage/memory"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.connection.create_table(:posts) { |t| t.text :image_data }

Shrine.storages[:cache] = Shrine.storages[:store] = Shrine::Storage::Memory.new

Shrine.plugin :activerecord
Shrine.plugin :validation_helpers

class ImageUploader < Shrine
  Attacher.validate { validate_max_size 5 }
end

class Post < ActiveRecord::Base
  include ImageUploader::Attachment(:image)
end

raw_file = StringIO.new("foobar")
post = Post.create(image: raw_file)
post.valid? # => false
post.errors.to_hash # => {:image=>["size must not be greater than 5.0 B"]}

cached_file = Shrine.upload(StringIO.new("foobar"), :cache)
post = Post.create(image: cached_file.data)
post.valid? # => false
post.errors.to_hash # => {:image=>["size must not be greater than 5.0 B"]}
```

> No but there is the option of passing the metadata up to the server. Which is what we have to do anyway.

This metadata generally doesn't have to be passed, it's kind of Uppy-specific. Also, the user can pass any data they want to that request, so even if you run validations there, you're still trusting the user to give you correct data, as you said.

As I said, client-side validations are the way to go there, and Uppy has nice ones built in. If you need to share data, like the maximum filesize of allowed MIME type list, you can put these values into constants and pass them to JavaScript via `data-*` attributes, e.g:

```rb
class ImageUploader < Shrine
  MAX_SIZE = 5*1024*1024
  # ...

  # this is run only on attachment assignment
  Attacher.validate do
    validate_max_size MAX_SIZE
    # ...
  end
end
```
```erb
<div data-controller="upload" data-upload-max-size="<%= ImageUploader::MAX_SIZE %>" ...>
</div>
```
```js
// Stimulus example
import { Controller } from 'stimulus'

export default class Upload extends Controller {
   // ...
   get maxSize() {
     return this.data.get('max-size')
   }
}
```

> If not, at what point does the ruby application gain access to the file to decide things like generate_location. I'm not sure by your explanation above if you agree that the promote method is the correct way to go?

Yes, promotion which is triggered automatically via Active Record callbacks is what puts the file in the correct place in the end.

**Closed by janko** 2020-06-19 12:52 UTC
