### ISSUE TITLE
image_url varies depending on file size

### ISSUE THREAD

**Issue by masudhossain** [shrinerb/shrine#374] opened 2019-04-11 03:14 UTC
When i upload very large files (5gb+) using the shrine gem, i noticed that the `image_url` is sometimes `s3.amazonaws.com/cache/` and sometimes it's `s3.amazongaws.com/store/`.

How come? Does saving the cache url to my DB as the link to it a bad idea? Does the cache link ever "go away"?

**Comment by hmistry** [comment] 2019-04-11 03:47
I'm going to assume the 2 url's are for the `cache` bucket and for the `store` bucket. When you first upload a file, it is uploaded to the `cache` bucket and then Shrine will process it and promote it if it passes validations to the `store` bucket. Look at the `storage` value in your `image_data` attribute of the record to see if the file has been promoted or not.

I'm closing this because this is not a bug or issue with Shrine. If you have more questions, please ask in our [Shrine Google groups](https://groups.google.com/forum/#!forum/ruby-shrine) as noted in our [Readme](https://github.com/shrinerb/shrine#resources) and we'll be happy to answer them. We prefer to limit issues for possible bug reports.

**Closed by hmistry** 2019-04-11 03:47 UTC

**Comment by janko** [comment] 2019-04-11 07:33
@masudhossain That's the expected behaviour when you're using `backgrounding`. The "promotion" that @hmistry mentioned will be delayed, and while it might not be noticeable with smaller files, with larger files you will see it, as it takes more time for cached files to be copied to the permanent location.

I'd only recommend storing the S3 URL to the DB if you know your files will be public, meaning you can use public URLs instead of expiring ones. But I don't see an advantage over generating the URL with Shrine.

The cached file doesn't get deleted automatically, as it's expected that you set a rule in your S3 bucket that automatically deletes old files. So you are in charge of when that gets deleted.

**Comment by masudhossain** [comment] 2019-04-13 22:57
Thanks for the responses. You guys have amazing issue handling on github. Keep it up!
