### ISSUE TITLE
Shrine attacher promoting but not updating/saving store

### ISSUE THREAD

**Issue by rssluca** [shrinerb/shrine#236] opened 2018-01-15 10:03 UTC
Running  v 2.8.0, and used code from example app.

Difference is that I am using a polymorphic Images table and referencing imageable. 

FYI everything works without backgrounding. 

Below is the log using backgrounding. Promoting works and I can see the data being passed but I do not know how to check if there is any other error downstream.

`
  SQL (2.2ms)  INSERT INTO "products" [...]
  SQL (0.6ms)  INSERT INTO "images" ("imageable_type", "imageable_id", "image_data", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["imageable_type", "Product"], ["imageable_id", 48], ["image_data", "{\"id\":\"4510eab3b8309440ab6b2e743b71d58d.jpg\",\"storage\":\"cache\",\"metadata\":{\"filename\":\"bottle.jpg\",\"size\":4510,\"mime_type\":\"image/jpeg\",\"width\":282,\"height\":500}}"], ["created_at", "2018-01-15 09:52:55.970691"], ["updated_at", "2018-01-15 09:52:55.970691"]]
   (1.7ms)  COMMIT
`

`
class PromoteJob
  include SuckerPunch::Job
  def perform(data)
    Rails.logger.info "SUCKERPUNCH PERFORMIMG TASK"
    Rails.logger.info data
    Shrine::Attacher.promote(data)
  end
end
`

`
SUCKERPUNCH PERFORMIMG TASK
{"attachment"=>"{\"id\":\"4510eab3b8309440ab6b2e743b71d58d.jpg\",\"storage\":\"cache\",\"metadata\":{\"filename\":\"bottle.jpg\",\"size\":4510,\"mime_type\":\"image/jpeg\",\"width\":282,\"height\":500}}", "record"=>["Image", "185"], "name"=>"image", "shrine_class"=>"ImageUploader", "action"=>"store", "phase"=>"store"}
`

**Comment by hmistry** [comment] 2018-01-15 10:31
You can use logging to check for errors. There is a [`logging` plugin](http://shrinerb.com/rdoc/classes/Shrine/Plugins/Logging.html) you can use if it meets your needs. 

If that's not the answer you're looking for, then please describe your problem more clearly and what you're trying to do. If possible, it would help us if you can provide the simplest self-contained example code to show the problem. There are [Sequel/ActiveRecord templates](https://github.com/janko-m/shrine/blob/master/CONTRIBUTING.md) if needed.

Also try searching for an answer through previous issues list and previous posts in the [ruby-shrine Google Group](https://groups.google.com/forum/#!forum/ruby-shrine), maybe it's been answered already.

Lastly, we'd like to keep Github issues for reporting known bugs and not for general how-to questions. Please post general questions like this in the [ruby-shrine Google Group](https://groups.google.com/forum/#!forum/ruby-shrine). Thanks.

**Comment by rssluca** [comment] 2018-01-15 10:47
Thanks hmistry.

, no errors are being shown.

I am not sure how I can be more clear:

- Promote is not saving to store and updating the image record. This is not the case when I do not use backgrounding (as in image is copied to store and record is updated correctly).

- I confirmed PromoteJob is called and the data parameters are passed correctly to Attacher.promote

- I am using logging plugin. I cannot see any logs once Shrine::Attacher.promote(data) is called by PromoteJob.

**Comment by janko-m** [comment] 2018-01-15 12:58
> I am not sure how I can be more clear

You described the problem clearly, you just haven't given us any Shrine-related code to work with. This is important, because otherwise we don't know where to start looking. As @hmistry said, ideally you should create a self-contained Ruby script which we could also run on our computers and get the same unexpected behaviour – that would guarantee that we would solve the issue very quickly.

Btw, this same issue has been reported [before](https://github.com/janko-m/shrine/issues/228), so it might be a bug in the `backgrounding` plugin, maybe with more recent versions of Rails. Note that currently if Shrine is not able to [find](https://github.com/janko-m/shrine/blob/fcb534d385d5ca2bbb87bc6ea0d8b7116a9879d3/lib/shrine/plugins/backgrounding.rb#L207) the record, it will [abort silently](https://github.com/janko-m/shrine/blob/fcb534d385d5ca2bbb87bc6ea0d8b7116a9879d3/lib/shrine/plugins/backgrounding.rb#L208-L211), because a record getting deleted while its attachment is being promoted isn't unexpected behaviour. It will also abort if the cached attachment has changed during promotion.

I would suggest that you also take a look at the [implementation](https://github.com/janko-m/shrine/blob/master/lib/shrine/plugins/backgrounding.rb) of the backgrounding plugin and see where the promotion might have aborted. One clue that I see is that the query for fetching the record by ID is missing from your logs. IMO that could only happen if the `Shrine::Attacher` class doesn't respond to `#find_record`, which would mean that the `activerecord` plugin is not loaded globally. **One way that could happen is if you loaded the `activerecord` plugin only for a certain uploader and not globally.**

If that's the case, then I totally agree that this is a mistake easily made, and we will try to make changes to the `backgrounding` plugin to address that.

**Comment by hmistry** [comment] 2018-01-15 22:08
@janko-m I'm glad you were able to figure it out. 😃 

@rssluca For me, it was not clear about the exact issue of your problem from your first posting. (Perhaps clear was not the best word to use.) I get that promoting works but update data doesn't, but no clues as to the type of error - invalid method/data, silent, ???. I'm not as intimately knowledgeable as Janko about all of Shrine's inner workings to fill in the gaps and so I needed more clues to be able to help. For me, phrasing it something like this would have been more helpful:

> When I use the backgrounding plugin, Shrine attacher fails to update/store the info in the record (reiterate the problem in the body). I've checked that promoting works, and that data is being passed from ? to ?, but then I get the following error (or ?) and the record does not save the new data. The record info is updated correctly when I remove the backgrounding plugin. Then state your question/goal - what are possible causes of failure or how does Shrine work in this case or how do I go about debugging this (this is what you eluded to by logging)... Last, provide supporting information like the backtrace, code snippets, configuration, versions of gems, etc.

This type of cohesive ordered phrasing allows one to quickly understand the working and non-working cases and identify area of problem and what type of help you're looking for. Your second comment was much much better except there's still no support information like code, configuration, backtrace,... to work with. Moving on as this is not the main issue, let's help you to get Shrine working.

I'll let Janko take it from here. If you find a solution, please let us know the cause and fix so we can help others with the same issue in future or improve Shrine so you don't encounter it again. Sorry I could not be more helpful.

**Comment by rssluca** [comment] 2018-01-16 05:51
@hmistry, you are right. My apology and thank you for your support!

@janko-m, thank you as well! The reason why I did not create a script yet is that I was not sure how to replicate my problem without actually releasing my entire app, since it follows the code in your example, and your example works fine!

I will try to build something that uses my code and provided it asap.

Thanks for your help guys.

Luca

**Comment by janko-m** [comment] 2018-01-16 11:07
Can you confirm that you loaded the activerecord plugin globally?

**Comment by rssluca** [comment] 2018-01-16 13:25
Yes loaded in shrine.rb initializer..

**Comment by rssluca** [comment] 2018-02-02 21:03
HI @janko-m,

I have added logging in backgrounding load_data method to check whether the activerecord plugin is loaded and it is. Class and ID are passed and the find_record method is indeed called but return a nil object.

I completely forgotten to mention that I am using the apartment gem for multitenancy (and I once again have to apologise).  I suspect the issue is that active record is querying the default schema and not finding a record.

**Comment by janko-m** [comment] 2018-02-24 15:00
@rssluca Sorry for the late answer. Yes, it would make sense that this is due to ActiveRecord not being able to find the record. You can override `Shrine::Attacher.find_record` with your own code:

```rb
Shrine.plugin :module_include
Shrine::Attacher.extend Module.new {
  def find_record(record_class, record_id)
    record_class.where(id: record_id).first # override here with your own implementation
  end
}
```

**Comment by janko** [comment] 2019-07-26 14:35
The new `backgrounding` approach for Shrine 3.0 will explicitly raise exceptions when promotion aborted (record was not found, attachment changed). Moreover, the Shrine user is now responsible for retrieving the database record inside the the background job, so they're able to handle multitenancy or sharding themselves.

Moreover, the `backgrounding` plugin now makes it easy to pass custom arguments from the controller into the background job.

These changes will be released in Shrine 3.0.

**Closed by janko** 2019-07-26 14:35 UTC

**Comment by texpert** [comment] 2019-08-02 13:31
For those, who will get the same behaviour - be sure not to mark the attacher_data attribute in the model as readonly!!! Had a full workday debugging this and just found it :)

**Comment by kobius** [comment] 2020-09-19 16:19
> For those, who will get the same behaviour - be sure not to mark the attacher_data attribute in the model as readonly!!! Had a full workday debugging this and just found it :)

Likewise, spent all of last night figuring this out thinking it was a problem with S3. This fixed it, thank you!
