### ISSUE TITLE
How to check and get validation error message for encrypted files

### ISSUE THREAD

**Issue by kashifnaseer** [shrinerb/shrine#283] opened 2018-07-16 11:23 UTC
In my Application, I want to give an error message when User tries to upload encrypted file. How i can do it using Shrine. 

**Here is my initializer:**

    require 'shrine'
    require "cloudinary"
    require "shrine/storage/cloudinary"

    Shrine.plugin :activerecord
    Shrine.plugin :cached_attachment_data # for forms
    Shrine.plugin :determine_mime_type
    Shrine.plugin :backgrounding
    Shrine.plugin :delete_promoted

    Shrine::Attacher.promote { |data| PromoteJob.perform_async(data) }
    Shrine::Attacher.delete { |data| DeleteJob.perform_async(data) }

**Uploader:**

    class DocumentUploader < Shrine
      plugin :validation_helpers
      plugin :pretty_location

      plugin :processing
      plugin :versions

       Attacher.validate do
        validate_mime_type_inclusion ['application/pdf']
      end
    end

**model:**

    class Document < ActiveRecord::Base
      extend Enumerize
      include DocumentUploader::Attachment.new(:doc)

When I create a Document having encrypted file, it should give validation error. How I can do it using shrine ?

**Comment by janko-m** [comment] 2018-07-16 15:39
Could you post a self-contained script that reproduces this behaviour (you can find a template in CONTIBUTING.md)? I'm not able to reproduce it myself, for me encrypted files fail validation, here is a script showing that it works:

```rb
require "active_record"
require "shrine"
require "shrine/storage/file_system"
require "open-uri"
require "openssl"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.connection.create_table(:documents) { |t| t.text :doc_data }

Shrine.storages = {
  cache: Shrine::Storage::FileSystem.new(Dir.tmpdir),
  store: Shrine::Storage::FileSystem.new(Dir.tmpdir),
}

Shrine.plugin :activerecord
Shrine.plugin :cached_attachment_data
Shrine.plugin :determine_mime_type
Shrine.plugin :backgrounding
Shrine.plugin :delete_promoted

Shrine::Attacher.promote { |data| Shrine::Attacher.promote(data) } # perform inline
Shrine::Attacher.delete { |data| Shrine::Attacher.delete(data) } # perform inline

class DocumentUploader < Shrine
  plugin :validation_helpers
  plugin :pretty_location

  plugin :processing
  plugin :versions

  Attacher.validate do
    validate_mime_type_inclusion ['application/pdf']
  end
end

class Document < ActiveRecord::Base
  include DocumentUploader::Attachment.new(:doc)
end

pdf = open("http://gahp.net/wp-content/uploads/2017/09/sample.pdf")

document = Document.create(doc: pdf)
document.valid? # => true

cipher = OpenSSL::Cipher.new("AES-128-CBC")
cipher.key = "a" * 16
cipher.encrypt

encrypted_pdf = Tempfile.new(["encrypted", ".pdf"], binmode: true)
encrypted_pdf.write cipher.update(File.binread(pdf.path)) + cipher.final
encrypted_pdf.rewind

document = Document.create(doc: encrypted_pdf)
document.valid? # => false
document.errors.to_h # => {:doc=>"isn't of allowed type (allowed types: application/pdf)"}
```

Since this doesn't appear to be a bug with Shrine, I will close this issue.

**Closed by janko-m** 2018-07-16 15:39 UTC
