### ISSUE TITLE
GIF Upload Fails

### ISSUE THREAD

**Issue by uurcankaya** [shrinerb/shrine#370] opened 2019-03-28 05:41 UTC
- Issues are for bug reports only.
- Have a question or unsure if it's a bug, then please inquire on the [ruby-shrine Google Group](https://groups.google.com/forum/#!forum/ruby-shrine).
---

### Brief Description
Gem returns error when uploading a GIF file

### Expected behavior
Upload with no warnings

### Actual behavior
Here is the warning: 

```
ImageProcessing::Error (Multi-layer image is being converted into a sin
gle-layer format. You should either process individual layers or set :allow_splitting
 to true. See https://github.com/janko-m/image_processing/wiki/Splitting-a-PDF-into-m
ultiple-images for how to process each layer individually.)
```

### Simplest self-contained example code to demonstrate issue
Provide a self-contained example code (see the [Sequel/ActiveRecord templates](https://github.com/shrinerb/shrine/blob/master/CONTRIBUTING.md)) to show the problem, and the full backtrace of any exception.

### System configuration
**Ruby version**: 2.5.3

**Shrine version**: 2.0

**Comment by uurcankaya** [comment] 2019-03-28 05:42
What is this warning really about? I could not understand

**Comment by janko** [comment] 2019-03-28 08:43
This error is coming from the `image_processing` gem, and the reason it's raised is because when ImageMagick is converting from a multi-layer format (GIF) into a single layer format (e.g. JPEG), then it creates multiple JPEGs for each GIF layer, naming each file `<destination-path>-<idx>`.

The solution is to add the `page: 0` loader option into the pipeline, so that you only process the first layer:

```rb
ImageProcessing
  .loader(page: 0)
  # ...
```

I see that the error message could be more explicit about the solution, I'll improve it.

**Comment by uurcankaya** [comment] 2019-03-28 18:42
@janko  thanks! I tried to add it here but could not get it to work:

`process(:store) do |io, context|
    original = io.download
    pipeline = ImageProcessing::MiniMagick.loader(page: 0).source(original)`

And just to make sure all other image files will work like this right? Or should it be for gif only?

**Comment by janko** [comment] 2019-03-29 09:22
> I tried to add it to the uploader.rb file but could not get it to work. :
> 
> ```rb
> process(:store) do |io, context|
>     original = io.download
>     pipeline = ImageProcessing::MiniMagick.loader(page: 0).source(original)
> ...
> ```
> 
> What am I doing wrong here?

It should work, I don't know what is wrong, "could not get it to work" is not really a lot to go on 😉 Does it throw an exception? Does nothing happen? Does the block get called at all?

> And if it only processes the first layer, the GIF probably will not be uploaded and converted to jpg? How can I upload gif files?

Yes, you can add the `:page` argument regardless of the source image type. It will work fine even if the source image is a single-layer type such as JPEG.

> ```rb
> process(:store) do |io, context|
>     original = io.download
>     original.close!
>     {original: io}
> ...
> ```
> 
> This also does not work, which I attempted to upload the file without processing.

This also should work, provided that you've loaded the `versions` plugin. If you're still having issues with any, please post a self-contained script that reproduces the issue to the ruby-shrine google group, you can find a template in CONTRIBUTING.md.

I'm closing this issue, as the original problem is purely related to the ImageProcessing gem, not Shrine. And for the remaining issues I believe there is some problem with your setup, I don't think the problem is in Shrine.

**Closed by janko** 2019-03-29 09:22 UTC
