### ISSUE TITLE
backgrounding plugin breaks manual call of `promote`

### ISSUE THREAD

**Issue by jrochkind** [shrinerb/shrine#333] opened 2018-12-03 21:16 UTC
You may sometimes want to manually call `promote`, and you ought to be able to. One use case is if the ordinary promotion failed for some reason, perhaps a reason related to external environment; maybe a disk filled up.  Now the model is an unpromoted state and will never change unless you promote it; maybe you want to manually call `promote` to do so. 

Backgrounding changes the nature of Attacher#promote, so it no longer works when called without any arguments.  Worse, it fails silently leaving you no way to know it did not actually save the record with promoted data (file on `store`, any processing or metadata extraction you have configured to happen during promotion), etc. 

This confused me greatly and took me all day to figure out, so I figured I'd report it! 

To verify, we can [look at an existing attacher_test](https://github.com/shrinerb/shrine/blob/master/test/attacher_test.rb#L158-L163), and just copy it the backgrounding_test, to be tested in the context of backgrounding. If you run that "#promote uploads the cached file to store" test _with_ `backgrounding` loaded -- it will fail.  I can supply a branch or PR with this failing test if this isn't clear. 

Why? Well, that's what took me a while to figure out. 

A) In a plain shrine uploader, on a model with an attachment, if you have configured things for `refresh_metadata` on `:store` (as is one suggested way to do things with `backgrounding`), calling `promote` will trigger metadata extraction, which _will_ result in a mutated in-memory model. The original in-memory model now has that new extracted metadata.  But then promotion goes on to call `update`, with, which the activerecord (or other ORM) plugin, just saves it to disk, along with that new metadata. 

B) The backgrounding plugin, however, will silently refuse to save it to disk.  Because it looks at the changed in-memory data, and sees that the thing stored in the db does not match, and therefore decides to abort promotion entirely, in it's overridden [swap](https://github.com/shrinerb/shrine/blob/master/lib/shrine/plugins/backgrounding.rb#L265-L271)

C) So how does backgrounding normally work at all? Well, backgrounding only breaks the no-argument use of `promote` -- or specifically, no _first_ argument given, so the default value is used, calling method `get`. But _ordinarily_ under backgrounding, a no-arg `promote` is never called. Instead backgrounding calls `promote` with [an explicit first arg, deserialized from a bg job argument](https://github.com/shrinerb/shrine/blob/master/lib/shrine/plugins/backgrounding.rb#L152). Since the explicit arg was created by deserializing some JSON, when passing it, `refresh/extract_metadata`  during storage does _not_ mutate the in-memory model, so it passes backgrounding's check in overridden "swap". 

So it only breaks `promote` manually called with no arguments, whcih doesn't _ordinarily_ happen in backgrounding "happy path". 

I suppose this could be considered not a bug -- why would you want to call `promote` manually with no args?  I think I've given a use case, but also it's just confusing if backgrounding changes the semantics of existing methods (to make them stop working when they used to work).  And led to me spending a day figuring out why things weren't working like I expected -- in this case in some of my local test setup code, but still. Adding a plugin probably shouldn't change the semantics of an existing method, to make something that would have worked fine before, now fail silently. Such gotchas make shrine seem a lot less predictable/reliable.

**Comment by jrochkind** [comment] 2018-12-03 21:22
Here's the branch with the failing test, demonstrating that `backgrounding` makes tests for `promote` that fail, that would pass without `backgrounding`. 

https://github.com/shrinerb/shrine/compare/master...backgrounding_breaks_no_arg_promote

**Comment by hmistry** [comment] 2018-12-03 21:50
Your scenario of needing to call `promote` manually is very valid. According to [this documentation](https://shrinerb.com/rdoc/files/doc/attacher_md.html#label-Backgrounding), have you tried using `attacher._promote`?

**Comment by jrochkind** [comment] 2018-12-03 22:21
`Attacher._promote`, with `backgrounding` installed,  would launch a bg job, whether I like it or not. If I'm doing it manually to recover from some error, I'd rather not launch a bg job. I may _already_ be in an error recovery bg job. Or I may be needing to do dozens/hundreds of them, and don't want to clog up my bg job queue.

**Comment by hmistry** [comment] 2018-12-03 22:45
> Attacher._promote, with backgrounding installed, would launch a bg job

I think it will if your promote block is `PromoteJob`, but not 100% sure. I agree it may not be suitable depending on what action you're looking to take on error.

> I'm not sure it's desirable for Backgrounding to change the public API from the normal looking `promote` to `_promote` that looks like a private API

It's not desirable at all. I think we need to establish a set of conventions and naming schemes and be consistent in the plugins. I get confused too. Or maybe Shrine already has it but it's too much for our little brains to track and predict because it's so flexible. 🙂

**Comment by janko-m** [comment] 2018-12-04 08:39
I'm sorry this was a frustrating experience for you 😞 

> Worse, it fails silently leaving you no way to know it did not actually save the record with promoted data (file on store, any processing or metadata extraction you have configured to happen during promotion), etc.

Yeah, I now think Attacher#promote should be raising an error when promotion failed or record is missing, and users should have to handle those exceptions in their background jobs if they need to. You're right that this can be a terrible debugging experience.

> Adding a plugin probably shouldn't change the semantics of an existing method, to make something that would have worked fine before, now fail silently. Such gotchas make shrine seem a lot less predictable/reliable.

Completely agree. I wasn't able to reproduce it with the following script, could you help me out? (of course, feel free to replace Sequel with ActiveRecord)

<details>

```rb
require "shrine"
require "shrine/storage/memory"
require "sequel"
require "stringio"

DB = Sequel.sqlite
DB.create_table :users do
  primary_key :id
  String :avatar_data
end

Shrine.storages = {
  cache: Shrine::Storage::Memory.new,
  store: Shrine::Storage::Memory.new,
}

Shrine.plugin :sequel, callbacks: false
Shrine.plugin :backgrounding

class ImageUploader < Shrine
  plugin :processing
  plugin :refresh_metadata

  process(:store) do |io, context|
    io.refresh_metadata!
    io
  end
end

class User < Sequel::Model
  include Shrine::Attachment.new(:avatar)
end

user = User.new
user.avatar_attacher.assign(StringIO.new("image"))
user.save
user.avatar_attacher.promote
user.avatar.storage_key # => "store"
```

</details><br>

> Here's the branch with the failing test, demonstrating that backgrounding makes tests for promote that fail, that would pass without backgrounding.

Note that this test is failing because you didn't persist the cached file to disk, so when the record gets reloaded in `Attacher#swap` there is no attachment. In that case aborting is correct, because if the user removed the attachment during promoting we shouldn't add back the stored version of the removed attachment.

> I understood the point of _promote vs promote to be to support backgrounding not breaking promote. I'm just confused though. If both _promote and promote exist.. but I'm supposed to use _promote if I have backgrounding installed... but maybe promote if I don't? Very confused.

`Attacher#_promote` means "if backgrounding plugin is loaded, spawn a background job, otherwise do it inline". `backgrounding` plugin overrides `Attacher#_promote` so that it doesn't just delegate to `Attacher#promote`. It didn't feel right to call it `#promote_later`, because it won't "promote later" unless the `backgrounding` plugin is loaded and background jobs are configured. But you're right that `#_promote` is a crappy name, it sounds internal when in fact it's not, suggestions welcome.

`Attacher#promote` is by all means still meant to be completely working when `backgrounding` plugin is loaded. Any breakage is a bug that needs to be fixed.

**Comment by jrochkind** [comment] 2018-12-04 15:39
@janko-m thanks for response and clarifications. 

## First, what I needed to to do to workaround in my current app

I'm having a lot of trouble making a reproduction. But I can say in my real app what I had to do to workaround. Instead of calling a promote with default argument, I do something like:

    attacher = model.avatar_attacher
    copy_of_data = attacher.uploaded_file(attacher.get)
    attacher.promote(copy_of_data, action: :store)

That is, instead of allowing the default argument to promote (which would be just `get`), I need to pass get to `uploaded_file` to make sure I have a different UploadedFile, and pass that. 

But I'm still having trouble making a repro case, I will explain...

## Why my original attempt at a failing test was faulty

OK, I understand now.  Do note that my failing test was taken [directly from the attacher_test](https://github.com/shrinerb/shrine/blob/master/test/attacher_test.rb#L158-L163) where it passes. 

But ok, I understand your point -- backgrounding, because of it's check in `swap`, adds an additional requirement that promotion can only work on a previously saved record.  While this is a change of behavior/semantics in promote and is maybe unfortunate (a test that passed without `backgrounding` still fails with it) -- this is NOT the problem I am running into in my app. I don't think. 

## Trying to take your reproduction case to reproduction

So ok, I started with the code you helpfully provided to try to turn that into a repro. There were several problems with your code. 

* Your code went to all that trouble to define an `ImageUploader`, then never actually used it. :)  You accidentally did `include Shrine::Attachment.new(:avatar)` in your record class. Took me an hour to figure out why nothing in the ImageUploader was actually happening at all. :( 

* To repro, we need some metadata that changes only in store and not in cache. (new metadata created or existing metadata changed, either way). That's what triggers. So I added a metadata block with a guard `if context[:action] == :store`, then I also had to make sure the refresh_metadata passed on the context (remember that doc fix?), `io.refresh_metadata!(context)`. 

I'm still not reproducing in your example like I am in the app. I'm not sure why. 

In my app, _when metadata has changed in store processing_, and I get to the [backgrounding swap override](https://github.com/shrinerb/shrine/blob/7ab986a10e055d08b69a731f99b7af5dbe007b43/lib/shrine/plugins/backgrounding.rb#L265-L268), it finds that `self.class.new(reloaded, name).read != read` -- because `read` has the metadata that had just been created in store but not yet persisted, but reloaded of course does not. 

However, in the repro starting from your script... `self.read` does **not** have the new metadata either (putting a debugger at that point), so the guard passes. 

I can't figure out why in my case `read` returns newly extracted (not yet persisted) data, but in your example repro it does not -- maybe activerecord doing something different here than sequel somehow?  

I'm not sure if I have any more time to bonk my head against this now, after now having spent about a day and a half on it (and having a local workaround), I might have to return to my app. But I'll see if anything else occurs to me, or if I can figure out how to change this to an activerecord demo in case that's it.

**Comment by jrochkind** [comment] 2018-12-04 15:52
OK, I changed the example to use activerecord... still does not repro for reasons discussed above. In backgrounding overridden `swap`, `self.read` in my actual app returns _new_ metadata just extracted in store phase; in the demo repro case, it does not. I can't figure out what would be different in my uploader, I can try to trim things out of my uploader and see if i can arrive at it... if I can make a good test case in my app. 

It's not too hard to set up a one-file reproduction for ActiveRecord, here's my current example (that is _not_ reproducing). 

<details>
```ruby
require "shrine"
require "shrine/storage/memory"
require "active_record"
require "action_controller/railtie"
require "stringio"
require 'byebug'

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: "promote_failure_repro")

ActiveRecord::Schema.define do
  create_table :users, force: true do |t|
    t.string :avatar_data
  end
end

Shrine.storages = {
  cache: Shrine::Storage::Memory.new,
  store: Shrine::Storage::Memory.new,
}

Shrine.plugin :activerecord, callbacks: false
Shrine.plugin :backgrounding

class ImageUploader < Shrine
  plugin :processing
  plugin :refresh_metadata
  plugin :add_metadata

  add_metadata(:value_from_store) do |io, context|
    if context[:action] == :store
      "value from store"
    end
  end

  process(:store) do |io, context|
    io.refresh_metadata!(context)
    io
  end
end

class User < ActiveRecord::Base
  include ImageUploader::Attachment.new(:avatar)
end


user = User.new
user.avatar_attacher.assign(StringIO.new("image"))
user.save
user.avatar_attacher.promote(action: :store, for_real_dont_fail: true)
puts user.avatar.metadata
puts user.avatar.storage_key # => "store"
```
</details>

**Comment by jrochkind** [comment] 2018-12-04 16:38
It is the ActiveRecord plugin's [convert_before_write override](https://github.com/shrinerb/shrine/blob/7ab986a10e055d08b69a731f99b7af5dbe007b43/lib/shrine/plugins/activerecord.rb#L143-L145) with custom json handling that helps triggers the problem. 

If i remove that override, the problem stops reproducing. 

I thought maybe changing `value` to `value.dup` or even `value.deep_dup` there would "fix" it -- but it did not. Very confused.

**Comment by hmistry** [comment] 2018-12-04 16:49
> Possibly could reproduce with sequel too, if sequel can support native json columns which shrine will treat speically for (de)serialization?

It supports JSON columns, add the `pg_json` extension. FYI.

```
DB = Sequel.postgres("shrine_test")
DB.extension :pg_json
```

**Comment by janko-m** [comment] 2018-12-04 18:15
Thanks a lot for reproducing. The issue is that Shrine is mutating the data column value. When the data column is a text column, we always `JSON.parse` it into a new Hash object, so it's safe to mutate the returned Hash object.

But with JSON columns ActiveRecord returns a Hash, and when `UploadedFile#refresh_metadata!` mutates it, that mutation persists next time the column is read via `Attacher#read`.

Either of these patches fixes the issue:

```diff
diff --git a/lib/shrine/plugins/activerecord.rb b/lib/shrine/plugins/activerecord.rb
index 1460cac..4c61221 100644
--- a/lib/shrine/plugins/activerecord.rb
+++ b/lib/shrine/plugins/activerecord.rb
@@ -144,6 +144,12 @@ class Shrine
           activerecord_json_column? ? value : super
         end
 
+        # If the data attribute represents a JSON column, we return the duped
+        # column value.
+        def convert_after_read(value)
+          activerecord_json_column? ? super.deep_dup : super
+        end
+
         # Returns true if the data attribute represents a JSON or JSONB column.
         def activerecord_json_column?
           return false unless record.is_a?(ActiveRecord::Base)
```
```diff
diff --git a/lib/shrine/plugins/backgrounding.rb b/lib/shrine/plugins/backgrounding.rb
index 2cd0656..4759597 100644
--- a/lib/shrine/plugins/backgrounding.rb
+++ b/lib/shrine/plugins/backgrounding.rb
@@ -265,7 +265,7 @@ class Shrine
         def swap(new_file)
           if self.class.respond_to?(:find_record)
             reloaded = self.class.find_record(record.class, record.id)
-            return if reloaded.nil? || self.class.new(reloaded, name).read != read
+            return if reloaded.nil? || self.class.new(reloaded, name).get != get
           end
           super
         end
```
```diff
diff --git a/lib/shrine/plugins/refresh_metadata.rb b/lib/shrine/plugins/refresh_metadata.rb
index 25fac31..5dec626 100644
--- a/lib/shrine/plugins/refresh_metadata.rb
+++ b/lib/shrine/plugins/refresh_metadata.rb
@@ -21,7 +21,7 @@ class Shrine
       module FileMethods
         def refresh_metadata!(context = {})
           refreshed_metadata = open { uploader.extract_metadata(self, context) }
-          metadata.merge!(refreshed_metadata)
+          @data = @data.merge("metadata" => metadata.merge(refreshed_metadata))
         end
       end
     end
```

I would like to apply all three of those, because they all make sense to me to prevent any similar issues in future cases. I don't know when I'll get around to do it, probably Friday. But if you feel like, feel free to make these patches accompanied with tests.

**Comment by janko-m** [comment] 2018-12-04 18:16
The 2nd patch works because `Attacher#get` returns a `Shrine::UploadedFile` object, and `Shrine::UploadedFile#==` ignores metadata when determining equality. https://github.com/shrinerb/shrine/blob/c92aef4fa83b73997a3a3a473467eeea3d1f96cd/lib/shrine/uploaded_file.rb#L222-L226

**Comment by jrochkind** [comment] 2018-12-04 19:57
Thanks Janko! 

> and Shrine::UploadedFile#== ignores metadata when determining equality.

I think ignoring metadata for determining "has the asset changed such that we shouldn't promote it" _probably_ makes sense? 

In my own code, where I needed to do something similar (has the asset changed concurrently such that we shouldn't do something) -- since it's my own code where I know what metadata is there, and I know I have a sha512 fingerprint in metadata -- I just use that.

**Comment by jrochkind** [comment] 2018-12-04 20:01
and hey, now I know how to make a one-file activerecord demo/example/reproduction for next time. :) Wow, that was a confusing one, in that it had to be _just_ the right combination of plugins and circumstances to trigger, and was very difficult to debug and figure out that combination. 

I feel like those patches should go along with some tests to keep the problem safe from happening... but I'm not really sure what the tests should be either. I noticed that neither activerecord plugin nor sequel plugin are actually currently tested....

**Comment by janko-m** [comment] 2018-12-13 01:40
This issue should be fixed by the two commits above ☝️

**Closed by janko-m** 2018-12-13 01:40 UTC

**Comment by jrochkind** [comment] 2019-02-14 21:08
Revisiting this as I review my code (and remove my workaround no longer required)

> Yeah, I now think Attacher#promote should be raising an error when promotion failed or record is missing, and users should have to handle those exceptions in their background jobs if they need to. You're right that this can be a terrible debugging experience.

Does that that still seem like a good idea and if so does it still need to be done?

**Comment by janko** [comment] 2019-02-14 23:06
> Does that that still seem like a good idea and if so does it still need to be done?

Yeah, it would make sense that it's up to the user to rescue these exceptions. I don't even think it would cause any real backwards compatibility problems if start raising these exceptions, as they would be occurring in background jobs (and the promotion/deletion should be idempotent). But maybe I'm wrong.

However, I think not everything should be raised. For example, while an attachment changing during promotion should probably be raised, having the cached attachment different than the one passed in background job arguments *before* the promotion even started should probably skip silently.

In any case, do you think it would be a good idea to add some debug logging into the deciding process? Maybe log conditionally if the `logging` plugin is loaded. Because I feel like these exceptions are to aid debugging, in which case logging might be more effective.
