### ISSUE TITLE
pretty_location at creation time with ActiveRecord

### ISSUE THREAD

**Issue by dvkch** [shrinerb/shrine#447] opened 2020-01-30 19:44 UTC
### Brief Description

I am facing an issue where the `pretty_location` plugin doesn't work too well with `ActiveRecord`'s models. 

If I upload attach a file at creation time, the generated `id` for the `cache` storage will not have the record's id in its path.

By inspecting `Attacher.promote(*)` it seems this work for the `store` storage by moving the file after it has been saved. It would be nice if in this phase the ``

I realize this is a low-priority issue, but having files in predictable places in the cache already allowed me once to retry failed uploads because if a missing allowed mime-type in my validations. It recovered hundreds of files.

I'm open to spending time on this and try some things in our already set-up app but the gem is too big for me and a starting point would be greatly appreciated.

In any case, thanks for considering and thank you for your hard work, I've been using Shrine for 3 months now and it is really an amazing and complete tool!

### Expected behavior

For a model `User` with id `1` and associated attribute `avatar`, the following code should place a file at `cache_prefix/user/1/avatar/uuid.ext`. 

### Actual behavior

The file appears at `cache_prefix/user/avatar/uuid.ext`

### Simplest self-contained example code to demonstrate issue

```
io = File.open('some_file.ext')
user = User.create(name: 'name', avatar: io)
```

### System configuration

**Ruby version**: 2.6.5

**Shrine version**: 3.2.1

**Comment by janko** [comment] 2020-02-03 12:28
The cached location will not include the record ID only when you're creating a new record. Shrine's intended behaviour is to treat file validations like other model validations, meaning if the validations fail, the record should not be persisted. However, the file still needs to be uploaded to temporary storage, which means there will be no record ID in the cache location.

From your description it seems that you want to persist the record even when file validation failed. You can do this by delaying the file attachment until after the record has been persisted:

```rb
photo = Photo.create(photo_params.except(:image))
photo.update(photo_params.slice(:image))
```

Note that if you choose to move to direct uploads, the record IDs will be lost again, as files will be uploaded separately from models.

As per contribution guidelines, GitHub issues are meant only for bug reports, so I'll close this issue. If something is still unclear, feel free to ask on the [Discourse forum](https://discourse.shrinerb.com/).

**Closed by janko** 2020-02-03 12:28 UTC

**Comment by dvkch** [comment] 2020-02-03 14:35
You're right that wouldn't make sense, since the object would never be persisted because of the validation error it would never have an ID and I would never be able to retry said upload. This case only works when attaching a file to a previously existing record.

What about when the validation succeeds and the object is persisted? I guess I'm not really sure about the cache storage real use. Is it only when uploading ? Will it be used after attached files have been promoted to :store ?

**Comment by janko** [comment] 2020-02-03 17:05
Shrine uploads the file to cache storage before file/model validation starts. This is to have consistent behaviour with other scenarios where an already cached file gets submitted to the application (on form redisplays or direct uploads).

No, cached files are not used anymore after they have been uploaded to permanent storage and the record has been updated with stored files. I will write a guide soon explaining the purpose of temporary storage in more detail.

But I'm not sure why you're asking about successful validation, as in that case the cached file will get promoted to permanent storage, which will have the record ID in the location.

**Comment by dvkch** [comment] 2020-02-03 17:07
I was asking for successful validations in case the files in the cache storage were to be used at some point, hence my question on that subject.

Thanks for everything, this is way clearer :)
