### ISSUE TITLE
validate_max_width and/or other dimension validations aren't working

### ISSUE THREAD

**Issue by rodloboz** [shrinerb/shrine#269] opened 2018-04-10 03:55 UTC
I'm trying to validate min width and height of a direct upload to S3 but the validation isn't able to get the width and the height values. I have registered the store_dimensiona plugin, but width and height don't seem to be saved to the metadata.
When adding a breakpoint inside the validation block, get.width and get.height both return nil.

When uploading images smaller than the set value, the uploader should return errors.

It is instead returning the deprecation warning regarding Shrine 3).

Here's my setup:

```ruby
# config/initializers/shrine.rb

require "shrine/storage/s3"

s3_options = {
  access_key_id:     ENV["AWS_ACCESS_KEY_ID"],
  secret_access_key: ENV["AWS_SECRET_ACCESS_KEY"],
  region:            ENV["AWS_REGION"],
  bucket:            ENV["AWS_BUCKET"],
}

Shrine.storages = {
  cache: Shrine::Storage::S3.new(prefix: "cache", **s3_options),
  store: Shrine::Storage::S3.new(prefix: "store", **s3_options),
}

Shrine.plugin :activerecord
Shrine.plugin :cached_attachment_data
Shrine.plugin :determine_mime_type
Shrine.plugin :store_dimensions
Shrine.plugin :backgrounding
Shrine.plugin :presign_endpoint, presign_options: -> (request) do
  { content_length_range: 0..20*1024*1024 }
end
```

```ruby
# image_uploader.rb

require 'image_processing/mini_magick'

class ImageUploader < Shrine

  include ImageProcessing::MiniMagick

  plugin :upload_options, cache: {acl: "public-read"}
  plugin :upload_options, store: {acl: "public-read"}
  plugin :logging, logger: Rails.logger
  plugin :validation_helpers
  plugin :pretty_location
  plugin :processing
  plugin :delete_promoted
  plugin :delete_raw
  plugin :versions
  plugin :recache

  Attacher.validate do
    validate_max_size 8.megabytes
    validate_min_width 1920
    validate_min_height 1080
    validate_extension_inclusion %w[jpg jpeg]
    validate_mime_type_inclusion ['image/jpg', 'image/jpeg']
  end
end
```

```ruby
# Gemfile

gem 'shrine'
gem 'aws-sdk'
gem 'roda'
gem 'fastimage'
gem 'image_processing'
gem 'mini_magick'
```

Ruby: 2.4.3
Rails: 5.1.5
Shrine: 2.9.0

Any help would be greatly appreciated :)

**Comment by hmistry** [comment] 2018-04-10 06:29
I'm unable to reproduce your issue with a test script. The dimensions are extracted and the dimension validators pass or fail promotion as expected. The errors are reported in AR model if it fails promotion.

Nothing stands out from the your code posted above... maybe something else is causing the issue. If you can create a simple test script, that can be helpful for us (refer to contributing doc in repo for sample script).

**Comment by janko-m** [comment] 2018-04-10 10:32
@rodloboz What image is this failing with? Shrine will give that deprecation warning when dimensions failed to be extracted, which means the problems is not in the validators but in the `store_dimensions` plugin.

Note that [FastImage](https://github.com/sdsykes/fastimage), the gem that `store_dimensions` plugin uses by default for extracting image dimensions, might not know how to extract dimensions from all types of images. I would recommend you try upgrading to Shrine 2.10 and try if you're getting better results with the `:mini_magick` analyzer (which should handle more image types). That way you can remove the `fastimage` dependency.

Unrelated, I noticed that you have a `roda` dependency, which was needed for `direct_upload` plugin, but is not used by `upload_endpoint` and `presign_endpoint` plugins anymore.

**Comment by rodloboz** [comment] 2018-04-10 14:44
@janko-m It was with regular jpegs and i've also tried with png files. Yes, I feel that for some reason the store_dimension wasn't getting the image dimensions,.

I did try the the mini_magick analyzer. I'll give it another try with Shrine 2.10. And thanks for pointing out the Roda dependency issues and also for writing such a great gem.

**Comment by hmistry** [comment] 2018-04-10 14:48
@janko-m FastImage can fail to extract dimensions on some jpegs?! If so, seems unreliable to be used for default unless other analyzers can fail too.

**Comment by janko-m** [comment] 2018-04-10 14:57
> I did try the the mini_magick analyzer. I'll give it another try with Shrine 2.10.

Note that the `:mini_magick` dimensions analyzer was just added in Shrine 2.10. If it does work, it would be great to get an image that fails so that we can reproduce this on our and, and decide whether FastImage should be the default (in this case probably not).

**Comment by rodloboz** [comment] 2018-04-10 15:02
I've upgraded to Shrine 2.10 but still aren't get to get the height or width of either PNG and JPEG images. Calling get.width and get.height inside the validation block always returns nil.

**Comment by janko-m** [comment] 2018-04-10 15:16
Cool, but you still haven't given us the image for which it fails, as we requested three times already. @hmistry told you he wasn't able to reproduce it, so without getting our hands on the failing image there is nothing we can do.

Also, when you upgraded to 2.10 did you make sure to use the `:mini_magick` dimensions analyzer, i.e. did you load the plugin with `Shrine.plugin :store_dimensions, analyzer: :mini_magick`?

**Comment by rodloboz** [comment] 2018-04-10 15:39
So you can find two of the images I have tried [here](https://drive.google.com/file/d/199wLkLcewKTzb9Jfwwrb4481u8h86FKo/view?usp=sharing) and [here](https://drive.google.com/file/d/1pv1EL-wEf9U_Gpv4bq0lEKEZuC3qQdfv/view?usp=sharing).

I loaded the `:strore_dimensions, analyzer: :mini_magick` on the ImageUploader file.

**Comment by janko-m** [comment] 2018-04-10 15:47
Thanks. Unfortunately, for some reason I'm getting "too many redirects" errors when trying to download these images from Google Drive 😕 (even after I copy them my drive). Is there an alternative way in which you can share them?

**Comment by rodloboz** [comment] 2018-04-10 16:15
Sure, what would be the best way for your? Here's a WeTransfer link
https://wetransfer.com/downloads/c49223813e8b33582f3905f24aa2e3e020180410161442/ca7c50bfcad3532f2855e00910b14a6d20180410161442/e4ac9c

**Comment by janko-m** [comment] 2018-04-10 16:15
I tried downloading the images by dragging their icons to Finder, but both of them extract dimensions correctly:

```rb
require "shrine"

image1 = File.open("/Users/janko/Downloads/brenda-godinez-228181-unsplash.jpg")
image2 = File.open("/Users/janko/Downloads/veggies.jpg")

Shrine.plugin :store_dimensions

p Shrine.extract_dimensions(image1)
p Shrine.extract_dimensions(image2)
```
```
[2079, 1386]
[700, 395]
```

But I'm not sure if those are originals, or the thumbnails processed by Google Drive. @rodloboz Do you get the same behaviour when executing the script above with your original images? If not, then those are not originals. If yes, then you'll need to post a minimal self-contained example the reproduces the problem.

**Comment by janko-m** [comment] 2018-04-10 16:17
Thanks, that worked. I'm getting successfully extracted dimensions from those images.

**Comment by janko-m** [comment] 2018-04-11 10:32
I'm closing this issue due to lack of information. If you still think this is a bug in Shrine, please provide a self-contained example that reproduces the bug.

**Closed by janko-m** 2018-04-11 10:32 UTC

**Comment by rodloboz** [comment] 2018-04-29 09:49
Ok I've finally figured out what was wrong and maybe this can be useful to anyone having a similar problem.

I was making direct uploads to S3 and therefore the server didn't have access to the original file data and the store_dimensions methods never got called to the original file.

Simply adding `plugin :restore_cached_data` to my file uploader solved the issue.
