### ISSUE TITLE
Shrine Image.delete, Aws::S3::Errors::AccessDenied 

### ISSUE THREAD

**Issue by uurcankaya** [shrinerb/shrine#351] opened 2019-02-19 02:11 UTC
- Issues are for bug reports only.
- Have a question or unsure if it's a bug, then please inquire on the [ruby-shrine Google Group](https://groups.google.com/forum/#!forum/ruby-shrine).
---

### Brief Description
S3 returns access denied error but everything seems to be correct including CORS settings. Wondering whether this is an issue related to how Shrine handles deletion

### Expected behavior
Image gets deleted from S3 with no errors

### Actual behavior
AWS returns AccessDenied error

### Simplest self-contained example code to demonstrate issue
Here is the cors 

```
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>GET</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader>Authorization</AllowedHeader>
</CORSRule>
<CORSRule>
    <AllowedOrigin>*</AllowedOrigin>
    <AllowedMethod>PUT</AllowedMethod>
    <AllowedMethod>POST</AllowedMethod>
    <AllowedMethod>DELETE</AllowedMethod>
    <MaxAgeSeconds>3000</MaxAgeSeconds>
    <AllowedHeader>*</AllowedHeader>
</CORSRule>
</CORSConfiguration>
```

### System configuration
**Ruby version**: 2.5.3

**Shrine version**: 2.14.0

**Comment by janko** [comment] 2019-02-19 09:29
When Shrine is deleting the image, CORS configuration doesn't matter, because you're using your AWS S3 credentials to do the deletion. What kind of permissions do your AWS S3 credentials have? According to the docs, they need to have at least `s3:ListBucket`, `s3:PutObject`, `s3:GetObject`, and `s3:DeleteObject` permissions.

It would be really helpful if you could produce a self-contained example that reproduces the issue. And it would be absolutely awesome if that script would also include the [creating keys on IAM](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/IAM/Client.html) and [creating the bucket](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/S3/Bucket.html#create-instance_method), because that way I'd know exactly the S3 configuration you have and would be able to reproduce it locally.

But for starters you can just describe what kind of credentials with which kind of policies are you using.

**Comment by janko** [comment] 2019-03-02 11:57
This is most likely a permission error, so I'm closing this. If you still believe this is a bug in Shrine, please post more details about your AWS keys.

**Closed by janko** 2019-03-02 11:57 UTC
