### ISSUE TITLE
Can't upload some files using the upload_endpoint plugin when they contain certain characters

### ISSUE THREAD

**Issue by aried3r** [shrinerb/shrine#307] opened 2018-10-30 15:34 UTC
### Brief Description
Trying to upload a file with `ü%` in their name (even when apart like in `über_pdf_with_1337%_leetness.pdf`) break the upload_endpoint plugin.

### Expected behavior
The file should be uploaded successfully.

### Actual behavior
An exception is thrown.

### Simplest self-contained example code to demonstrate issue

I couldn't figure out how to talk to the plugin directly with the issue template, but here's the stacktrace. Also attached is a PDF that makes it misbehave. [über_pdf_with_1337%.pdf](https://github.com/shrinerb/shrine/files/2530331/uber_pdf_with_1337.pdf)

```
STORE[upload] DocumentUploader 1 file (0.0s)

Encoding::UndefinedConversionError ("\xCC" from ASCII-8BIT to UTF-8):

ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/core_ext/object/json.rb:38:in `encode'
ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/core_ext/object/json.rb:38:in `to_json'
ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/core_ext/object/json.rb:38:in `to_json'
ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/json/encoding.rb:57:in `to_json'
/usr/local/rbenv/versions/2.5.3/lib/ruby/2.5.0/json/common.rb:224:in `generate'
/usr/local/rbenv/versions/2.5.3/lib/ruby/2.5.0/json/common.rb:224:in `generate'
ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/json/encoding.rb:102:in `stringify'
ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/json/encoding.rb:35:in `encode'
ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/json/encoding.rb:22:in `encode'
ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/core_ext/object/json.rb:41:in `to_json'
ruby/2.5.0/gems/shrine-2.12.0/lib/shrine.rb:928:in `to_json'
ruby/2.5.0/gems/shrine-2.12.0/lib/shrine/plugins/upload_endpoint.rb:235:in `make_response'
ruby/2.5.0/gems/shrine-2.12.0/lib/shrine/plugins/upload_endpoint.rb:191:in `handle_request'
ruby/2.5.0/gems/shrine-2.12.0/lib/shrine/plugins/upload_endpoint.rb:173:in `block in call'
ruby/2.5.0/gems/shrine-2.12.0/lib/shrine/plugins/upload_endpoint.rb:169:in `catch'
ruby/2.5.0/gems/shrine-2.12.0/lib/shrine/plugins/upload_endpoint.rb:169:in `call'
ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/mapper.rb:48:in `serve'
ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/journey/router.rb:52:in `block in serve'
ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/journey/router.rb:35:in `each'
ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/journey/router.rb:35:in `serve'
ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/routing/route_set.rb:840:in `call'
ruby/2.5.0/gems/exception_notification-4.2.2/lib/exception_notification/rack.rb:41:in `call'
ruby/2.5.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
ruby/2.5.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
ruby/2.5.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
ruby/2.5.0/gems/rack-2.0.5/lib/rack/tempfile_reaper.rb:15:in `call'
ruby/2.5.0/gems/rack-2.0.5/lib/rack/etag.rb:25:in `call'
ruby/2.5.0/gems/rack-2.0.5/lib/rack/conditional_get.rb:38:in `call'
ruby/2.5.0/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'
ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
ruby/2.5.0/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:232:in `context'
ruby/2.5.0/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:226:in `call'
ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/cookies.rb:670:in `call'
ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
ruby/2.5.0/gems/railties-5.2.1/lib/rails/rack/logger.rb:38:in `call_app'
ruby/2.5.0/gems/railties-5.2.1/lib/rails/rack/logger.rb:26:in `block in call'
ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/tagged_logging.rb:71:in `block in tagged'
ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/tagged_logging.rb:28:in `tagged'
ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/tagged_logging.rb:71:in `tagged'
ruby/2.5.0/gems/railties-5.2.1/lib/rails/rack/logger.rb:26:in `call'
ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
ruby/2.5.0/gems/request_store-1.4.1/lib/request_store/middleware.rb:19:in `call'
ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
ruby/2.5.0/gems/rack-2.0.5/lib/rack/method_override.rb:22:in `call'
ruby/2.5.0/gems/rack-2.0.5/lib/rack/runtime.rb:22:in `call'
ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
ruby/2.5.0/gems/actionpack-5.2.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
ruby/2.5.0/gems/rack-2.0.5/lib/rack/sendfile.rb:111:in `call'
ruby/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:524:in `call'
```

### System configuration
**Ruby version**: 2.5.3

**Shrine version**: 2.12.0

**Comment by hmistry** [comment] 2018-10-30 18:19
Hi Anton

Thanks for reporting this and providing us with the necessary info. We'll look into it and get back to you.

**Comment by janko-m** [comment] 2018-10-30 21:49
This appears to be a known bug in Rack: https://github.com/rack/rack/issues/1078

When Rack parses the multipart form data, the filename ends up in binary encoding instead of UTF-8:

```rb
{:filename=>"\xC3\xBCber_pdf_with_1337%_leetness.pdf",
 :type=>nil,
 :name=>"file",
 :tempfile=>#<File:/var/folders/k7/6zx6dx6x7ys3rv3srh0nyfj00000gn/T/RackMultipart20181030-88870-1xy9bsb.pdf>,
 :head=>"Content-Disposition: form-data; name=\"file\"; filename=\"\xC3\xBCber_pdf_with_1337%_leetness.pdf\"\r\n"}
```

And Ruby's JSON serializer seems to require the strings to be in UTF-8 encoding. Since that Rack issue hasn't been addressed since 2016, we'll add a workaround in Shrine. A simple `String#force_encoding` call should do the trick.

**Comment by jrochkind** [comment] 2018-10-30 22:07
i think it could be argued it's not a Rack bug -- if the specs/standards are unclear on what encoding that should be interpreted as (or even unclear as to there being such a thing as encodings other than ascii) -- as I suspect they are -- Rack can't really do anything but leave it `binary`. 

But usually _Rails_ takes care of such things for us. It might be a Rails bug. 

It might also be way too confusing for anyone to ever figure out whose bug it is. If there's an easy workaround for shrine, that's awesome.

**Comment by janko-m** [comment] 2018-10-30 22:16
Yeah, that makes sense, I agree that this Rack behaviour is probably not a bug. It's definitely not a bug in Rails, because mounted Rack apps are called with the raw Rack env hash, so there is no Rails context anymore unless what Rails added/modified on the env hash. I see the same behaviour with Roda.

**Comment by janko-m** [comment] 2018-10-31 19:20
Rack's multipart parser appears to behave differently with the `%`, returning the filename in binary encoding:

```rb
{:filename=>"\xC3\xBCber_pdf_with_1337%_leetness.pdf",
 :type=>nil,
 :name=>"file",
 :tempfile=>#<File:/var/folders/k7/6zx6dx6x7ys3rv3srh0nyfj00000gn/T/RackMultipart20181031-16504-bi73lc.pdf>,
 :head=>"Content-Disposition: form-data; name=\"file\"; filename=\"\xC3\xBCber_pdf_with_1337%_leetness.pdf\"\r\n"}}
```

and without the `%`, returning the filename in UTF-8 encoding:

```
{:filename=>"über_pdf_with_1337_leetness.pdf",
 :type=>nil,
 :name=>"file",
 :tempfile=>#<File:/var/folders/k7/6zx6dx6x7ys3rv3srh0nyfj00000gn/T/RackMultipart20181031-16504-1x00so.pdf>,
 :head=>"Content-Disposition: form-data; name=\"file\"; filename=\"\xC3\xBCber_pdf_with_1337_leetness.pdf\"\r\n"}}
```

It seems strange, but that's the current Rack behaviour. In any case, it should be fixed by https://github.com/shrinerb/shrine/pull/308, which I'll merge shortly.

**Closed** 2018-10-31 19:33 UTC

**Comment by aried3r** [comment] 2018-11-01 12:59
Awesome, thanks for fixing it so quickly! Now of course the obligatory question is, will there be a new release soon or should I rather point my Gemfile to `master` for the time being? 😅

**Comment by janko-m** [comment] 2018-11-01 13:47
There is still one important new feature that we want to include in the next release (improved versions plugin), and that might take a week or two, so for the time being you can point your Gemfile to `master`.

**Comment by jrochkind** [comment] 2018-11-01 14:51
Might it make sense to release a patch release now (1.2.1?) with just the bug fix?

**Comment by janko-m** [comment] 2018-11-04 23:15
Version 2.13.0 was released, which includes this fix.
