### ISSUE TITLE
store_dimensions plugin bug

### ISSUE THREAD

**Issue by nicksarafa** [shrinerb/shrine#287] opened 2018-08-12 02:35 UTC
### Brief Description
I'm having an issue with the `:store_dimensions` plugin

Upon file upload, I receive the following error 

```undefined method `arity' for nil:NilClass
/Users/ns/.rvm/gems/ruby-2.4.1/gems/shrine-2.9.0/lib/shrine/plugins/store_dimensions.rb:58:in `extract_dimensions'
/Users/ns/.rvm/gems/ruby-2.4.1/gems/shrine-2.9.0/lib/shrine/plugins/store_dimensions.rb:91:in `extract_dimensions'
/Users/ns/.rvm/gems/ruby-2.4.1/gems/shrine-2.9.0/lib/shrine/plugins/store_dimensions.rb:79:in `extract_metadata'
/Users/ns/.rvm/gems/ruby-2.4.1/gems/shrine-2.9.0/lib/shrine.rb:360:in `get_metadata'
/Users/ns/.rvm/gems/ruby-2.4.1/gems/shrine-2.9.0/lib/shrine.rb:302:in `_store'
/Users/ns/.rvm/gems/ruby-2.4.1/gems/shrine-2.9.0/lib/shrine/plugins/versions.rb:223:in `_store'
/Users/ns/.rvm/gems/ruby-2.4.1/gems/shrine-2.9.0/lib/shrine.rb:235:in `store'
/Users/ns/.rvm/gems/ruby-2.4.1/gems/shrine-2.9.0/lib/shrine.rb:213:in `upload'
/Users/ns/.rvm/gems/ruby-2.4.1/gems/shrine-2.9.0/lib/shrine.rb:632:in `cache!'
/Users/ns/.rvm/gems/ruby-2.4.1/gems/shrine-2.9.0/lib/shrine.rb:523:in `assign'
/Users/ns/.rvm/gems/ruby-2.4.1/gems/shrine-2.9.0/lib/shrine/plugins/remote_url.rb:122:in `remote_url='
/Users/ns/.rvm/gems/ruby-2.4.1/gems/shrine-2.9.0/lib/shrine/plugins/remote_url.rb:98:in `image_remote_url='```

### Expected behavior
I expect the image to upload with the image dimensions

### Actual behavior
The console throws an error

### Simplest self-contained example code to demonstrate issue
```
class ImageUploader < Shrine
  plugin :store_dimensions
end
```

### System configuration
**Ruby version**: 2.4.1

**Shrine version**: 2.9.0

**Comment by hmistry** [comment] 2018-08-12 06:54
I'm not able to reproduce your bug with v2.9.0. You can use my test script below to debug your issue. Or you can try upgrading to the latest Shrine version. If you find the bug, then post the test script that demonstrate the bug.

```
require "active_record"
require "shrine"
require "shrine/storage/file_system"
require "tmpdir"
require "open-uri"
require "byebug"

Shrine.plugin :activerecord
Shrine.storages = {
cache: Shrine::Storage::FileSystem.new(Dir.tmpdir, prefix: "cache"),
store: Shrine::Storage::FileSystem.new(Dir.tmpdir, prefix: "store"),
}

class MyUploader < Shrine
  plugin :store_dimensions
end

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Base.connection.create_table(:posts) { |t| t.text :image_data }

class Post < ActiveRecord::Base
include MyUploader::Attachment.new(:image)
end

file = File.new("../test/fixtures/image.jpg")
post = Post.create(image: open(file))
puts post.image_data

# output
# {"id":"676298026b35f1e3850fdeac17de49d5.jpg","storage":"store","metadata":{"filename":"image.jpg","size":6147,"mime_type":null,"width":100,"height":67}}
```

**Comment by janko-m** [comment] 2018-08-12 07:36
It seems that you've passed `nil` as the `:analyzer`. You should either pass a symbol or proc or nothing.

Closing, as this doesn't appear to be a bug in Shrine.

**Closed by janko-m** 2018-08-12 07:36 UTC
